// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTD2DP6O60vqUV1RPR4ZTZCO3N3foi9K8',
    appId: '1:348279615785:web:83fe20c480461ef5ad4738',
    messagingSenderId: '348279615785',
    projectId: 'notification-d557e',
    authDomain: 'notification-d557e.firebaseapp.com',
    storageBucket: 'notification-d557e.firebasestorage.app',
    measurementId: 'G-PJ6R3KF5GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOSL_8Ec-hbBMfzwkF3F-lPZ4-VfANYY',
    appId: '1:348279615785:android:31b75c597a964efead4738',
    messagingSenderId: '348279615785',
    projectId: 'notification-d557e',
    storageBucket: 'notification-d557e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi8H7kLug1McRLH46MunCiHA9WH_Aoa7k',
    appId: '1:348279615785:ios:0d79f73ccb63d511ad4738',
    messagingSenderId: '348279615785',
    projectId: 'notification-d557e',
    storageBucket: 'notification-d557e.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi8H7kLug1McRLH46MunCiHA9WH_Aoa7k',
    appId: '1:348279615785:ios:0d79f73ccb63d511ad4738',
    messagingSenderId: '348279615785',
    projectId: 'notification-d557e',
    storageBucket: 'notification-d557e.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTD2DP6O60vqUV1RPR4ZTZCO3N3foi9K8',
    appId: '1:348279615785:web:6a52fb9532cb02dfad4738',
    messagingSenderId: '348279615785',
    projectId: 'notification-d557e',
    authDomain: 'notification-d557e.firebaseapp.com',
    storageBucket: 'notification-d557e.firebasestorage.app',
    measurementId: 'G-LFK20YW627',
  );
}
